
version: '3.9'
services:
  yolosservices:
    build: 
      context: ..
      dockerfile: .docker/Dockerfile
      args:
        - IMAGE_TAG=ubuntu:20.04
        - PYTHON_VERSION=3.9.18
        - PYCHARM_VERSION=2023.2.1
    image: skrjtech/yolos:latest
    container_name: yolosprojectcontainer
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/yolos
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]