
version: '3.9'
services:
  yolosservices:
    build: 
      context: ..
      dockerfile: .docker/Dockerfile
    image: skrjtech/yolos:latest
    container_name: yolosprojectcontainer
    tty: true
    restart: always
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ..:/yolosProject
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]